### ISSUE TITLE
'fee' is ignored in operation settings

### ISSUE THREAD

**Issue by rognierbenoit** [madfish-solutions/thanoswallet-dapp#8]
Hi, it seems that the operation fee is ignored in the following instruction:

```
tezos.wallet.at(contractAddress).then(contract => {
    contract.methods.start(UnitValue).send({ amount : price, fee : '0.1' }).then(
    ...)
}
```
It would be very useful to forward the fee parameter as well.
Thanks.

**Comment by serg-plusplus** [comment]
Hi, @rognierbenoit!
Sorry for the late response.

Currently `fee` parameter is not transferred to the wallet. Because it is not displayed to the owner of the wallet, and calculate automatically. We have plans to implement this. After that - the `fee` stuff will work.
